# render.yaml (should be at the ROOT of your GitHub repository)
services:
  - type: web # <-- Is this "web" in your Render settings? Or "worker"?
    name: remityn # <-- Does this EXACTLY match your service name on Render? Case-sensitive!
    env: node # Or specify your Node version: node 20 / node 18 etc.
    # plan: free # (Optional, Render infers or uses default)
    # region: oregon # (Optional, Render infers or uses default)
    # rootDir: server # (Optional, if also set in UI, UI might take precedence or conflict if different)
    aptPackages:
      # --- Debian/Ubuntu packages required by Playwright's Chromium ---
      # Essential runtime libraries
      - libc6
      - libgcc1
      - libstdc++6
      # Core X11 and graphics libraries
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxrandr2
      - libxrender1
      - libxss1
      - libxtst6
      # Font and text rendering
      - libfontconfig1
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - fonts-liberation # Recommended for headless browsers
      # Image format libraries
      - libjpeg62-turbo # or libjpeg-turbo8
      - libexpat1 # XML parser
      # Accessibility and UI
      - libatk1.0-0
      - libatk-bridge2.0-0
      # Networking and security
      - libnspr4
      - libnss3
      - ca-certificates # For HTTPS
      # Audio
      - libasound2
      # Other common dependencies
      - libcups2
      - libdbus-1-3
      - libgbm1
      - libglib2.0-0
      # Utilities
      - lsb-release
      # Might also need:
      # - libgdk-pixbuf2.0-0 # For some image operations
      # - libgtk-3-0 # Large, try to avoid if not strictly necessary
      # - xdg-utils
      # - wget
    # If your Build Command & Start Command are in Render UI, you don't need them here
    # buildCommand: "npm install && npx playwright install chromium" # (This would be relative to Root Directory)
    # startCommand: "npm start"